---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170518094744"
generator:
  name: "NewRugProject"
  group: "atomist"
  artifact: "rug-rugs"
  version: "0.30.1"
  origin:
    repo: "https://github.com/atomist/rug-rugs.git"
    branch: "4babf5df7ea909f42b0390b5c38fb8d3632b810d"
    sha: "4babf5d"
  parameters:
    - "owner": "leojpod"
    - "description": "bamboo grows fast, so will this elm toolbox!   ... hopefully ..."
    - "version": "0.1.0"

